# Generated by Django 4.1 on 2022-08-29 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storage", "0002_alter_url_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
